#version 450
#extension GL_GOOGLE_include_directive : enable
#include "Shader/SceneParameter.glsl"
#include "Shader/GpuParticleData.glsl"

layout(local_size_x=32,local_size_y=1,local_size_z=1) in;
void main()
{
  uint index = gl_GlobalInvocationID.x;
  if( index < maxParticleCount)
  {
    uint useListIndex = atomicAdd(headIndex, 1);
    indices[useListIndex] = index;

    gpuParticleElements[index].isActive = 0;
  }
}
